### ISSUE TITLE
how can i use this package

### ISSUE THREAD

**Issue by pishguy** [cerbero90/notifiable-exception#1]
here this below code is sample? or we should implement that?

```php
use Cerbero\NotifiableException\Notifiable;
use Cerbero\NotifiableException\Notifies;
use Exception;

class UrgentException extends Exception implements Notifiable
{
    use Notifies;
}
```

and using `try` and `cache` should be in code? or this library can get error without them?

**Comment by Faks** [comment]
It's very straight forward but it required deep Laravel knowledge and framework in general to utilize its full potential, but this use case explains that you can use it as your own custom exception that is notifiable.
But there is also a way to integrate deeper with laravel core and have all exceptions notifiable if interested in this approach we can in private chat talk about it and the price for such integration :).

**Comment by cerbero90** [comment]
Please read the instructions in the README.md file and feel free to let me know if something is not clear 👍
